import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Header from "@/components/Header";
import { MagnifyingGlassIcon, MicrophoneIcon } from "@heroicons/react/24/solid";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Google Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <form className="flex flex-col items-center mt-40">
        <Image
          width={300}
          height={100}
          className="object-cover"
          src="https://cdn.freebiesupply.com/images/large/2x/google-logo-transparent.png"
          alt=""
        />
        <div className="flex w-full border border-gray max-w-[90%] mx-auto hover:shadow-lg focus-within:shadow-lg px-5 py-3 rounded-full sm:max-w-lg lg:max-w-2xl">
          <MagnifyingGlassIcon className="h-5 text-gray-500 mr-3" />
          <input type="text" className="flex-grow focus:outline-none" />
          <MicrophoneIcon className="h-5 text-gray-500" />
        </div>
        <div className="flex flex-col sm:flex-row w-[50%] space-y-2 mt-8 sm:space-y-0 sm:space-x-4 justify-center">
          <button className="btn">Google Search</button>
          <button className="btn">I am feeling lucky</button>
        </div>
      </form>
    </>
  );
}
